### PR TITLE
Add E2E tests to Pull Requests

### PR DESCRIPTION
**Pull request by ryanemerson**
This should result in the db-syncer image being created and then executed in the E2E testsuite with the most recent Operator code and cache-manager images.

### CODE REVIEW

**Comment by jabolina** [comment]
The test failed on the `PublishChangesTest#testRolledBackNotPublished:249` running with Oracle. I guess it's only a matter of the CDC events not being detected before the timeout. Locally I noticed that changes in Oracle take some time to be identified, but 10s is a delay I've never seen before. I'll trigger the CI again.

**Comment by ryanemerson** [comment]
I just realised that because we have `maven.test.failure.ignore=true` the E2E tests will always attempt to run regardless of whether we have failures or not. It's not a big deal, but we should figure out a way to check if failures have occurred and then fail the PR action accordingly.

This is also required for the cache-manager https://github.com/gingersnap-project/cache-manager/issues/80

**Comment by jabolina** [comment]
Since the failures are unrelated I'll merge this. I'll be working on MS support in tests, hopefully fixing these failures, and looking into not running E2E in case of test failures.

**Comment by jabolina** [comment]
Merged. Thanks @ryanemerson

**Pull request merged**
