### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by ryanemerson**
Needs https://github.com/gingersnap-project/db-syncer/pull/79 first.

### CODE REVIEW

**Comment by ryanemerson** [comment]
I've removed the Debezium upgrade for now as that had related failures that need to be looked into in detail.

**Comment by jabolina** [comment]
Are those failures due to the updates or flaky executions? I can take a look if you want. It seems that one does not simply get a green CI :dizzy_face: :dizzy_face:

**Comment by ryanemerson** [comment]
I think `MultiCacheManagerTest` is flakey in general. It's also failing for Oracle on https://github.com/gingersnap-project/db-syncer/pull/82/files

**Comment by pruivo** [comment]
as far as my maven skill allows, only debezium uses antlr at runtime. 
I would force the use of antlr version. After https://github.com/gingersnap-project/db-syncer/blob/a154a7c25ae880e2164b3ed7fe728e3bb845348f/pom.xml#L35
add
```xml
      <!-- use the same version as debezium. Update it when debezium is updated -->
      <dependency>
        <groupId>org.antlr</groupId>
        <artifactId>antlr</artifactId>
        <version>4.8</version>
      </dependency>
      <dependency>
        <groupId>org.antlr</groupId>
        <artifactId>antlr4-runtime</artifactId>
        <version>4.8</version>
      </dependency>
```

**Comment by pruivo** [comment]
@ryanemerson needs rebase. I believe the only change required is removing the `,` here: https://github.com/gingersnap-project/db-syncer/blob/a154a7c25ae880e2164b3ed7fe728e3bb845348f/src/test/java/io/gingersnapproject/metrics/MetricsResourceTest.java#L96

**Comment by ryanemerson** [comment]
We still have failures, but these are also present on other PRs https://github.com/gingersnap-project/db-syncer/pull/83 so I don't think they're related to the upgrades.

**Comment by jabolina** [comment]
The failures are not related! Just trying to find out what's going on, it seems it is a concurrency problem because of the Debezium engines starting concurrently and failing to create the log mining table:

https://github.com/debezium/debezium/blob/f8c0e477e6a0aeffad004e8d48d5042843f87655/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/CommitLogWriterFlushStrategy.java#L99-L101

I think doing something like: https://github.com/ryanemerson/db-syncer/compare/upgrades...jabolina:db-syncer:re/upgrades could solve it. The rule that is registered automatically is causing the issue.

**Review by pruivo — APPROVED** [review]

**Comment by jabolina** [comment]
I'll open a follow-up to fix the test failures.

**Pull request merged**
