### PR TITLE
Basic setup for running multiple providers

### PR DESCRIPTION
**Pull request by jabolina**
Changing some files and adding a resource for Postgres. I tried running with MS SQL, but setting up everything is a pain, as we need to enable the agent, restart, and use an additional tool container. I'll try that another time.

Right now is only something to run with multiple DBs, and we know at least it can start. I'll add actual tests in another PR. And we can copy the resource to other projects if needed.

### CODE REVIEW

**Comment by jabolina** [comment]
It looks like our cache-manager in the latest never becomes ready.

**Comment by ryanemerson** [comment]
> It looks like our cache-manager in the latest never becomes ready.

I know the problem, creating a PR to fix :+1:

**Comment by ryanemerson** [comment]
@jabolina https://github.com/gingersnap-project/cache-manager/pull/19

Sorry for the delay. I went down a rabbit hole of working on semi-related changes before realising my efforts were futile and I should just create the simple PR :sweat:

**Comment by ryanemerson** [comment]
The test is still failing on `main`. I think it's because of two reasons:

1. We start the cache-manager before the DB
2. The `quarkus.datasource.reactive.url` property is hardcoded in the cache-manager `application.properties`. We need to set this at runtime so that the correct host:port combo for the DB container is used.

**Comment by jabolina** [comment]
We are going to try an approach based on profiles, trying to get some more isolation between the resources. With that in place, we'll start with the tests, first at least on E2E and then some functional.

**Comment by ryanemerson** [comment]
Thanks @jabolina

**Pull request merged**
